# Swagger toggle configuration
swagger:
  enable: true

# Log Configuration
logging:
  pretty-print: true
  level:
    com: INFO
    com.service: TRACE
    org.springframework: INFO

# General configuration
spring:
  application:
    name: demo-Service
  jackson.default-property-inclusion: NON_NULL

# Server Configuration
server:
  port: 8090


info:
  app:
    name: ^project.name^
    version: ^project.version^
    description: ^project.description^

security:
  # your-service-secret
  app-secret: 92d4f86r-8768a-4b79m-8a7a-c97d33722019
